---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 12.18

inputs:
  - name: dp-performance-dashboard

outputs:
  - name: build

run:
  path: dp-performance-dashboard/ci/scripts/build.sh
